[versions]
kotlin = "2.2.21"
org-jetbrains-dokka = "2.1.0"
org-ow2-asm = "9.9"

[libraries]
asm = { module = "org.ow2.asm:asm", version.ref = "org-ow2-asm" }
asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "org-ow2-asm" }
classgraph = "io.github.classgraph:classgraph:4.8.184"
gradle-dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "org-jetbrains-dokka" }
gradle-kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-nexus-publish-plugin = "io.github.gradle-nexus.publish-plugin:io.github.gradle-nexus.publish-plugin.gradle.plugin:2.0.0"
gradle-node-plugin = "com.github.node-gradle.node:com.github.node-gradle.node.gradle.plugin:7.1.0"
gradle-plugin-plugin = "com.gradle.plugin-publish:com.gradle.plugin-publish.gradle.plugin:2.0.0"
jackson-databind = "tools.jackson.core:jackson-databind:3.0.3"
kotlinx-metadata-jvm = "org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.9.0"
logback = "ch.qos.logback:logback-classic:1.5.22"
spring-webmvc = "org.springframework:spring-webmvc:7.0.1"
spring-boot-starter-web = "org.springframework.boot:spring-boot-starter-web:4.0.0"